"""Regenerate `sim_splits.json`: the eval holdout and the half-size subset of mm's sim.

Run this only if the sim dataset is rebuilt. The checked-in JSON is what the configs
read, so the split travels with the code and every arm withholds exactly the same
episodes -- which is the only reason offline eval can rank the three arms against each
other at all.

    uv run python configs/mm/make_sim_splits.py --root /workspace/mm/sim_v21
    uv run python configs/mm/make_sim_splits.py --episodes-parquet meta/episodes/chunk-000/file-000.parquet

WHY BOTH SPLITS ARE PICKED BY STRIDE RATHER THAN AT RANDOM
    Episode length falls monotonically-ish with episode index in this dataset (447
    frames at ep 0 down to ~300 by ep 30), because the ManiSkill generator got faster at
    the task as it went. So a contiguous split is biased in trajectory length, and with
    only 50 episodes a random draw is unreliable too: one unlucky seed puts most of the
    long episodes on one side. A fixed stride interleaves them by construction, needs no
    seed, and is trivially auditable -- and it lands both splits within 2% of their
    target frame share, which random selection does not reliably do at n=50.

WHY THE HALF-SPLIT IS DEFINED AS EXCLUSIONS
    `MixtureSource.exclude_episodes` withholds episodes from the training stream without
    touching the dataset on disk, so all three arms read ONE dataset root and differ
    only in what they exclude. The alternative -- building a physically separate
    half-size dataset -- gives a second root to keep in sync and renumbers episodes
    0..N-1, which would silently invalidate the holdout indices.
"""

from __future__ import annotations

import argparse
import json
import pathlib

# One entry per 10 episodes, offset 4, so the holdout is spread across the run of the
# generator rather than clustered at either end.
HOLDOUT_STRIDE = 10
HOLDOUT_OFFSET = 4
# Of what remains, keep every other episode for the half-size arm.
HALF_STRIDE = 2
HALF_OFFSET = 0


def episode_lengths_from_root(root: pathlib.Path) -> list[int]:
    """Read per-episode frame counts from a LeRobot root, v2.1 or v3.0."""
    jsonl = root / "meta" / "episodes.jsonl"
    if jsonl.exists():  # v2.1
        rows = [json.loads(line) for line in jsonl.read_text().splitlines() if line.strip()]
        rows.sort(key=lambda r: r["episode_index"])
        return [int(r["length"]) for r in rows]

    parquets = sorted((root / "meta" / "episodes").rglob("*.parquet"))  # v3.0
    if parquets:
        return episode_lengths_from_parquet(parquets)

    raise FileNotFoundError(f"no meta/episodes.jsonl and no meta/episodes/**.parquet under {root}")


def episode_lengths_from_parquet(paths: list[pathlib.Path]) -> list[int]:
    import pandas as pd  # lazy: pandas is not an openpi runtime dep, only a v3.0 reader needs it

    frame = pd.concat([pd.read_parquet(p) for p in paths]).sort_values("episode_index")
    return [int(x) for x in frame["length"]]


def select(lengths: list[int]) -> dict:
    total_episodes = len(lengths)
    total_frames = sum(lengths)

    holdout = [i for i in range(total_episodes) if i % HOLDOUT_STRIDE == HOLDOUT_OFFSET]
    train = [i for i in range(total_episodes) if i not in set(holdout)]
    half_keep = train[HALF_OFFSET::HALF_STRIDE]
    # What the half-size arm excludes is the holdout PLUS the episodes it drops. The two
    # are merged here so a config can pass one list and cannot forget the holdout.
    half_exclude = sorted(set(holdout) | (set(train) - set(half_keep)))

    def frames(episodes: list[int]) -> int:
        return sum(lengths[i] for i in episodes)

    return {
        "_comment": "Generated by configs/mm/make_sim_splits.py -- do not hand-edit.",
        "total_episodes": total_episodes,
        "total_frames": total_frames,
        "holdout_episodes": holdout,
        "holdout_frames": frames(holdout),
        "train_episodes": len(train),
        "train_frames": frames(train),
        "half_exclude_episodes": half_exclude,
        "half_train_episodes": len(half_keep),
        "half_train_frames": frames(half_keep),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--root", type=pathlib.Path, help="LeRobot dataset root (v2.1 or v3.0)")
    source.add_argument("--episodes-parquet", type=pathlib.Path, nargs="+", help="v3.0 meta/episodes parquet(s)")
    parser.add_argument("--out", type=pathlib.Path, default=pathlib.Path(__file__).parent / "sim_splits.json")
    args = parser.parse_args()

    lengths = (
        episode_lengths_from_root(args.root)
        if args.root is not None
        else episode_lengths_from_parquet(list(args.episodes_parquet))
    )
    splits = select(lengths)
    args.out.write_text(json.dumps(splits, indent=2) + "\n")

    total = splits["total_frames"]
    print(f"wrote {args.out}")
    for label, episodes, frames in (
        ("holdout   ", len(splits["holdout_episodes"]), splits["holdout_frames"]),
        ("train     ", splits["train_episodes"], splits["train_frames"]),
        ("train/half", splits["half_train_episodes"], splits["half_train_frames"]),
    ):
        print(
            f"  {label}: {episodes:3d} eps  {frames:6,d} frames  {100 * frames / total:5.2f}%  {frames / 1800:.2f} min"
        )


if __name__ == "__main__":
    main()
